# https://render.com/docs/blueprint-spec
services:

  - type: web
    name: aggrechans
    runtime: image
    image:
      url: ghcr.io/walkure/aggrechans:latest-webhook
    region: singapore
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: aggrechans-redis
          property: connectionString
      - key: DISPATCH_CHANNEL
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false

  - type: redis
    name: aggrechans-redis
    region: singapore
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru
